#!/usr/bin/env python3
"""
midi_to_mips.py
---------------
Converts a MIDI file into a MIPS assembly file (.asm) that uses MARS
syscall 31 (synchronous MIDI tone) and syscall 32 (sleep) to play music.

Usage:
    python midi_to_mips.py input.mid [output.asm] [--track N] [--instrument N] [--volume N]

Dependencies:
    pip install mido
"""

import argparse
import sys
from pathlib import Path

try:
    import mido
except ImportError:
    sys.exit(
        "ERROR: 'mido' is not installed.\n"
        "Install it with:  pip install mido"
    )


# ---------------------------------------------------------------------------
# MARS syscall constants
# ---------------------------------------------------------------------------
SYSCALL_MIDI_OUT_SYNC = 31   # play tone and WAIT until done
SYSCALL_SLEEP         = 32   # sleep for $a0 milliseconds
SYSCALL_EXIT          = 10   # exit program


def ticks_to_ms(ticks: int, tempo_us: int, ticks_per_beat: int) -> int:
    """Convert MIDI ticks to milliseconds given the current tempo."""
    if ticks_per_beat == 0:
        return 0
    ms = (ticks * tempo_us) / (ticks_per_beat * 1000)
    return max(0, round(ms))


def collect_events(mid: mido.MidiFile, track_index: int):
    """
    Flatten one track (or all merged tracks) into a list of
    (time_ms, event_type, pitch, velocity, instrument) tuples.

    event_type is 'note_on' or 'gap'.
    """
    DEFAULT_TEMPO = 500_000  # microseconds per beat (= 120 BPM)
    tpb = mid.ticks_per_beat

    if track_index == -1:
        # Merge all tracks into a single timeline
        track = mido.merge_tracks(mid.tracks)
    else:
        if track_index >= len(mid.tracks):
            sys.exit(
                f"ERROR: Track {track_index} does not exist. "
                f"The file has {len(mid.tracks)} track(s) (0-indexed)."
            )
        track = mid.tracks[track_index]

    events = []
    tempo      = DEFAULT_TEMPO
    instrument = 0       # General MIDI program number (0 = Acoustic Grand Piano)
    current_ms = 0

    for msg in track:
        # Accumulate delta time
        delta_ms   = ticks_to_ms(msg.time, tempo, tpb)
        current_ms += delta_ms

        if msg.type == "set_tempo":
            tempo = msg.tempo

        elif msg.type == "program_change":
            instrument = msg.program

        elif msg.type == "note_on" and msg.velocity > 0:
            events.append({
                "time_ms":    current_ms,
                "pitch":      msg.note,
                "velocity":   msg.velocity,
                "instrument": instrument,
            })

        # note_off / note_on with velocity 0 are ignored;
        # duration is handled by the gap to the next note.

    return events


def build_asm(events: list, default_instrument: int, default_volume: int) -> str:
    """
    Turn the list of note events into a MIPS assembly string.

    Strategy:
      - Sort events by time.
      - Between consecutive notes, emit a syscall 32 (sleep) for the gap.
      - For each note, emit syscall 31 with pitch, duration, instrument, volume.
        Duration = time until the next event (or a default of 400 ms for the last note).
    """
    if not events:
        return _empty_asm()

    events = sorted(events, key=lambda e: e["time_ms"])

    lines = []
    lines.append("# Auto-generated by midi_to_mips.py")
    lines.append("# Plays a MIDI melody using MARS syscall 31 (MIDI out sync).")
    lines.append("#")
    lines.append("# syscall 31 arguments:")
    lines.append("#   $a0 = pitch      (0-127, MIDI note number)")
    lines.append("#   $a1 = duration   (milliseconds)")
    lines.append("#   $a2 = instrument (0-127, General MIDI program)")
    lines.append("#   $a3 = volume     (0-127)")
    lines.append("")
    lines.append(".text")
    lines.append(".globl main")
    lines.append("main:")
    lines.append("")

    prev_time = 0

    for i, ev in enumerate(events):
        gap_ms = ev["time_ms"] - prev_time

        # --- emit a sleep for any gap before this note ---
        if gap_ms > 0:
            lines.append(f"    # sleep {gap_ms} ms")
            lines.append(f"    li   $v0, {SYSCALL_SLEEP}")
            lines.append(f"    li   $a0, {gap_ms}")
            lines.append( "    syscall")
            lines.append("")

        # --- determine note duration ---
        if i + 1 < len(events):
            duration_ms = events[i + 1]["time_ms"] - ev["time_ms"]
            duration_ms = max(1, duration_ms)
        else:
            duration_ms = 400   # give the last note a sensible default

        instrument = default_instrument if default_instrument >= 0 else ev["instrument"]
        volume     = default_volume if default_volume >= 0 else ev["velocity"]

        # Clamp to valid MIDI ranges
        pitch      = max(0, min(127, ev["pitch"]))
        duration_ms= max(1, duration_ms)
        instrument = max(0, min(127, instrument))
        volume     = max(0, min(127, volume))

        lines.append(f"    # note: pitch={pitch}  dur={duration_ms}ms  "
                     f"inst={instrument}  vol={volume}")
        lines.append(f"    li   $v0, {SYSCALL_MIDI_OUT_SYNC}")
        lines.append(f"    li   $a0, {pitch}")
        lines.append(f"    li   $a1, {duration_ms}")
        lines.append(f"    li   $a2, {instrument}")
        lines.append(f"    li   $a3, {volume}")
        lines.append( "    syscall")
        lines.append("")

        prev_time = ev["time_ms"]

    # --- exit ---
    lines.append("    # exit")
    lines.append(f"    li   $v0, {SYSCALL_EXIT}")
    lines.append( "    syscall")
    lines.append("")

    return "\n".join(lines)


def _empty_asm() -> str:
    return (
        "# No note events found in the selected track.\n"
        ".text\n.globl main\nmain:\n"
        f"    li   $v0, {SYSCALL_EXIT}\n    syscall\n"
    )


def print_track_info(mid: mido.MidiFile):
    """Print a summary of all tracks so the user can choose one."""
    DEFAULT_TEMPO = 500_000
    tpb = mid.ticks_per_beat
    print(f"\nMIDI file info:")
    print(f"  Type       : {mid.type}")
    print(f"  Tracks     : {len(mid.tracks)}")
    print(f"  Ticks/beat : {tpb}")
    print()
    for i, track in enumerate(mid.tracks):
        note_count = sum(
            1 for m in track
            if m.type == "note_on" and m.velocity > 0
        )
        print(f"  Track {i:2d}: \"{track.name}\"  —  {note_count} note(s)")
    print()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(
        description="Convert a MIDI file to a MIPS .asm file for MARS."
    )
    p.add_argument("input",  help="Input MIDI file (.mid / .midi)")
    p.add_argument("output", nargs="?", help="Output .asm file (default: <input>.asm)")
    p.add_argument(
        "--track", "-t", type=int, default=-1,
        help="Track index to convert (0-based). Default: -1 = merge all tracks."
    )
    p.add_argument(
        "--instrument", "-i", type=int, default=-1,
        help="Override GM instrument for all notes (0-127). Default: use MIDI values."
    )
    p.add_argument(
        "--volume", "-v", type=int, default=-1,
        help="Override volume for all notes (0-127). Default: use MIDI velocity."
    )
    p.add_argument(
        "--info", action="store_true",
        help="Print track info and exit without converting."
    )
    return p.parse_args()


def main():
    args = parse_args()

    midi_path = Path(args.input)
    if not midi_path.exists():
        sys.exit(f"ERROR: File not found: {midi_path}")

    try:
        mid = mido.MidiFile(str(midi_path))
    except Exception as e:
        sys.exit(f"ERROR: Could not parse MIDI file: {e}")

    print_track_info(mid)

    if args.info:
        return

    events = collect_events(mid, args.track)
    print(f"Collected {len(events)} note event(s) "
          f"from {'all tracks (merged)' if args.track == -1 else f'track {args.track}'}.")

    asm = build_asm(events, args.instrument, args.volume)

    out_path = Path(args.output) if args.output else midi_path.with_suffix(".asm")
    out_path.write_text(asm, encoding="utf-8")
    print(f"Assembly written to: {out_path}")


if __name__ == "__main__":
    main()